### ISSUE TITLE
roaming fence

### ISSUE THREAD

**Issue by uwer** [iwpnd/pyle38#251]
Hi Guys,
could you confirm that the nearby.fence function supports roaming fences ? I could not find that option in the implementation.
If it is not are you planning to add it?
Cheers
Uwe

**Comment by iwpnd** [comment]
Hey @uwer, its currently not supported out of the box, but you should be able to pass custom commands to:

`await tile38.command('SETHOOK', [ option, option, option ])`.

**Comment by iwpnd** [comment]
closing this, feel free to reopen if necesary
