### ISSUE TITLE
set point not supporting z values 

### ISSUE THREAD

**Issue by uwer** [iwpnd/pyle38#310]
the set.point command signature does not allow for a z value

**Comment by iwpnd** [comment]
that's correct. let me see what the effort is, maybe I can do it this evening.

**Comment by uwer** [comment]
Thanks Ben

I can probably get around it using 'command', but that is not really the
point.
Thanks for the quick response

Uwe

**Comment by iwpnd** [comment]
let me know if that works for you @uwer and thanks for reaching out 🙏

**Comment by uwer** [comment]
Hi Ben,

thank you for the update !!!
and man, what a prompt response, I wish my commercial contacts were that
responsive...
if there is anything ever i can do, pls let me know.
One question though, why exclude python version pre 3.10? There current
standard deployment of all LTE platforms is generally 3.9 (some even 3.8).

Cheers
uwe

**Comment by iwpnd** [comment]
🤔 I think something I added recently required 3.10. don't really remember. older versions of pyle support <3.10 tho.

if I have a minute I look into it.
