### ISSUE TITLE
Error adding fields during SET operation.

### ISSUE THREAD

**Issue by jeafreezy** [iwpnd/pyle38#370]
Gooday,

Thank you for this great library.

Please I am trying to set some attributes using `fields()` in the SET operation, but I'm running into errors.

```Python
from pydantic import BaseModel
import asyncio
from pyle38.tile38 import Tile38


class DataModel(BaseModel):
    IpSender: Optional[str] = None
    PortSender: Optional[int] = None
    Latitude: Optional[float] = None
    Longitude: Optional[float] = None
    IsValid: bool = False
    ...

async def main():
    tile38 = Tile38(url="redis://localhost:9851")
    
    payload = DataModel(...) # some data are passed here.
    response = await tile38.set(channel_name, unique_id)
                .point(float(payload.Latitude),float(payload.Longitude))
                .fields(payload.model_dump()) #error is happening here
                .exec()
   return response


asyncio.run(main())
```

* It returns an error:

`Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.`

* But I expected it to SET the fields without any error.

### Environment

* OS:  Windows
* FastAPI Version: 0.103.2
* Pyle38 version:0.11.1
* Python version: 3.10

**Comment by iwpnd** [comment]
Hey there, the error is straight forward. Either make sure to filter out unpopulated fields when exporting your DataModel, or give sensible defaults.

**Comment by jeafreezy** [comment]
Thank you for your response.

I have tried that using the 'exclude_none=True' argument in the model_dump() method and it filters out all the None, however I still experience errors when I have boolean values in my model. E.g  {"key": True/False} . The fields seems to only support `str`, `float` and `int`.

Kindly help. Thanks

**Comment by jeafreezy** [comment]
Thank you for the insight. This is what I did and it worked. I used 'true''/'false' approach and automaticlaly it was transformed by pyle38 to true and false.

**Comment by jeafreezy** [comment]
I used this code in the pydantic model.

```Python

    @validator("DataValidity")
    def validate_bool(cls, value):
        if value:
            return Validity.VALID_TRANSFORMED.value if value else Validity.INVALID_TRANSFORMED.value
        return value
```

In the enums I have:


```
class Validity(enum.Enum):
    ...
    VALID_TRANSFORMED = 'true'
    INVALID_TRANSFORMED= 'false'
```

**Comment by jeafreezy** [comment]
> Im sorry I didn't get the last part. Do you have a working solution now? 🙂

Yes I do. Thank you!
