### ISSUE TITLE
Not able to set points

### ISSUE THREAD

**Issue by GuptaAman08** [iwpnd/pyle38#54]
Hey,

Getting below error
`unknown command OUTPUT, with args beginning with: JSON,`

I am passing the url `redis://localhost:6379` while instantiating Tile38(). (`tile38 = Tile38(os.environ.get("REDIS_URL"))`)

This line works fine.
I get error in the just next line of code which is `await tile38.set('fleet', id_).point(station[0], station[1]).exec(),` where id_ is a string value and station[0] and station[1] is an float value

My Redis Server is running on localhost:6379

I tried a lot but was not able to figure out what's going wrong. Can anybody help me with this?

**Comment by iwpnd** [comment]
Hi @GuptaAman08, this client is written for [tile38](https://github.com/tile38). You're trying to connect to to a plain redis server. If you want to test it you can either [follow the installation instructions on the tile38 website](https://tile38.com/topics/installation), or start the [docker-compose.yml](https://github.com/iwpnd/pyle38/blob/main/docker-compose.yml) in this repository to get a tile38 instance running.

**Comment by GuptaAman08** [comment]
I see. Thanks !!
