### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by iwpnd** [iwpnd/pyle38#6]
blank

**Comment by GuptaAman08** [comment]
Hey,

Getting below error 
`unknown command `OUTPUT`, with args beginning with: `JSON`, `

I am passing this url `redis://localhost:6379` while instantiating Tile38().  (`tile38 = Tile38(os.environ.get("REDIS_URL"))`)

This line works fine.
I get error in the just next line of code which is  `await tile38.set('fleet', id_).point(station[0], station[1]).exec()`

My Redis Server is running on localhost:6379

I tried a lot but was not able to figure out what's going wrong. Can anybody help me with this?
