### ISSUE TITLE
Add ability to pipeline set commands

### ISSUE THREAD

**Issue by btcpcs** [iwpnd/pyle38#70]
Feature request
--
Add .pipeline() method

I'm using pyle38 and working on a visualization/simulation app. The ability to pipeline commands would be great.

**Comment by iwpnd** [comment]
Hi, thank you for using pyle38 and thank you for your post. 

Unfortunately I don't agree with you that pyle38 should take care of lining up tasks. You can use solid existing frameworks for that, like [pypeln](https://github.com/cgarciae/pypeln). 

Hope that points you into the correct direction. :)

Have a nice weekend 👋🏻

**Comment by btcpcs** [comment]
Thanks.  Understood. Great client library by the way.  I'll drop down to the redis client to use the Tile38 RESP pipeline commands

https://github.com/tidwall/tile38/issues/49

Thanks for the quick response

________________________________

**Comment by iwpnd** [comment]
If you elaborate a little on what you’re planning to do, maybe I can help out. I’m not sure I understand yet. :)

**Comment by btcpcs** [comment]
Hi Ben,

I am looking for the ability SET or GET 10's or 100s of commands, Pipelines (in Redis and Tile38) provide a way to transmit multiple commands to the Redis/Tile38 server in one transmission or in one network call. This saves having to do separate SET's for each Point, etc.

Something like this....
tile38 = Tile38(url="redis://localhost:9851")
pipeline = tile38.pipeline(transaction=False)
pipeline.set("fleet", "truck1").point(52.25,13.37)
pipeline.set("fleet", "truck2").point(58.88,12.39)
pipeline.set("fleet", "truck3").point(50.25,15.50)
pipeline.set("fleet", "truck4").point(57.25,13.37)
pipeline.execute()

Hope this makes it more clear.

**Comment by iwpnd** [comment]
Ah, gotcha.

If it's about saving time that's why I choose an async api in the first place.

Given a timer function

```python
import asyncio
import random
import functools
import time
from contextlib import contextmanager

def duration(func):
    @contextmanager
    def wrapping_logic():
        start_ts = time.time()
        yield
        dur = time.time() - start_ts
        print("{} took {} seconds".format(func.__name__, dur))

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        if not asyncio.iscoroutinefunction(func):
            with wrapping_logic():
                return func(*args, **kwargs)
        else:

            async def tmp():
                with wrapping_logic():
                    return await func(*args, **kwargs)

            return tmp()

    return wrapper
```

**Comment by btcpcs** [comment]
OK. This is great. I see how Pyle38 handles this. It is the connection and batch request issue you mention below that I am trying to solve. 

> Since some limitation on the connection pool to redis prevent me from bombarding Tile38 with 10.000 requests in parallel I batch my SETs in packs of 99. This mean on every execution in the loop I send 99 requests to Tile38 asynchronously.

Here is the aioredis library using a pipeline to issue multiple commands. Tile38 does not have transactions so that would need to be set to False, but I would expect that this code would both improve both the insert speed of your samples above and potentially solve the multiple connection issue.

import asyncio
import aioredis
async def main():
    redis = aioredis.from_url("redis://localhost")
    await redis.delete("foo", "bar")
    async with redis.pipeline(transaction=True) as pipe:
       # send your batch of commands (SET's, etc.) inside of the pipe command. 
        res = await pipe.incr("foo").incr("bar").execute()
      # This should be very fast compared to a loop and multiple sets and use only one connection. 
    print(res)

if __name__ == "__main__":
    asyncio.run(main())

**Comment by iwpnd** [comment]
I understand, yet some use cases involve a client issuing one command, others might distribute it across a set of workers.
I think pyle38 sits somewhere in between and can do either or.

**Comment by btcpcs** [comment]
Yes, the async nature of Pyle38 is nice in that it allows for some  flexibility on handling these types of situations.  Appreciate the back and forth on this and it probably makes sense to keep the client as is.
________________________________

**Comment by iwpnd** [comment]
closing this now, thank you 🙏
